image: rust

stages:
  - test
  - deploy

.cargo-cache:
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/.cargo
  cache:
    key: cargo
    paths:
      - target
      - $CARGO_HOME

cargo-test:
  extends: .cargo-cache
  stage: test
  script:
    - cargo test

pages:
  stage: deploy
  extends: .cargo-cache
  script:
    - cargo doc --no-deps
    - mv target/doc public
  artifacts:
    paths:
      - public
  only:
    - master
